spring.application.name=tapro-backend

server.port=${PORT:8080}

app.upload-dir=${APP_UPLOAD_DIR:uploads}

app.frontend-url=${FRONTEND_URL:http://localhost:3000}
app.frontend-urls=${FRONTEND_URLS:http://localhost:3000,http://127.0.0.1:3000,https://tapro-frontend.vercel.app}

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

app.jwt.secret=${JWT_SECRET:TAPRO_LOCAL_DEV_SECRET_KEY_2026_01}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
app.email.dev-mode=${APP_EMAIL_DEV_MODE:true}

spring.mail.host=${MAIL_HOST:}
spring.mail.port=${MAIL_PORT:1025}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH:false}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_SMTP_STARTTLS_ENABLE:false}
spring.mail.properties.mail.smtp.connectiontimeout=${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
spring.mail.properties.mail.smtp.timeout=${MAIL_SMTP_TIMEOUT:5000}
spring.mail.properties.mail.smtp.writetimeout=${MAIL_SMTP_WRITE_TIMEOUT:5000}
